# Generated by Django 5.0.1 on 2024-01-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_createlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlist',
            name='s_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
