# Generated by Django 5.0.1 on 2024-01-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_createlist_s_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.BooleanField(default=1)),
                ('select_song', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateList',
        ),
    ]
