# Generated by Django 5.0.1 on 2024-01-12 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_createplaylist_delete_createlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createplaylist',
            name='select_song',
        ),
        migrations.AddField(
            model_name='createplaylist',
            name='playlist_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='createplaylist',
            name='song_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Music.addsong'),
        ),
    ]
